### ISSUE TITLE
Group-D03-05-Operations by authenticated principals on offers

### ISSUE THREAD

**Issue by josrojrom1** [josrojrom1/C1.04.02#127]
Operations by authenticated principals on offers:
List the offers in the system and show their details.

Estimated time -> 3 h

**Comment by josrojrom1** [comment]
Operations by authenticated principals on offers:
List the offers in the system and show their details.


Estimated time -> 3 h

**Comment by Samalbalat** [comment]
Tarea completada
Se puede observar al entrar con un usuario autenticado en la pestaña con el mismo nombre en el campo desplegable
Este incluye la lista y el detalle al picar sobre una oferta en concreto
Todavía no están implementadas las restricciones a la hora de Crear la oferta, pero los datos por defecto dan indicaciones de los parámetros mínimos que cumplen con dicha restricción

**Comment by Samalbalat** [comment]
Actualización: 
Hay que eliminar la opción de crear desde autenticados dado que no va estipulada, en resumen sobran funcionalidades para este tipo de usuario
