### ISSUE TITLE
Group-D04-10-Produce a complete test suite - Sam

### ISSUE THREAD

**Issue by josrojrom1** [josrojrom1/C1.04.02#219]
Complete test suite for requirement 21)

[Mandatory] Operations by any principals on peeps:
List the peeps and show their details.
Publish a peep.  By default, the nick must be kept blank if the principal is anonymous; otherwise, it must be filled with the principal’s full name; anyway, it can be changed at will.

Realizar : 1 test positivo, 1 test negativo, 1 test de hacking

tiempo estimado: 3h

**Comment by Samalbalat** [comment]
Completado en sus diferentes secciones
